// D22 catalog builder — pure (no I/O, no import.meta), so the CI gates can
// import it under jest. The CLI shell that writes files is generate-schema.mjs.
// Spec: docs/superpowers/specs/2026-07-03-d22-naturalized-schema-design.md
import { createHash } from "crypto";
import { getAllStandardTagEntries } from "../src/dicom.lookup.js";
import {
    parseVm,
    VR_SCALAR,
    MULTI_VR,
    VR_FORMATS,
    EXCLUDED_TAGS
} from "./schemaRules.mjs";

const SCHEMA_VERSION = "1.0.0";

function bareTag(paren) {
    // "(0008,0008)" -> "00080008"
    const m = paren.match(/^\((\w{4}),(\w{4})\)$/);
    if (!m) {
        throw new Error(`unexpected tag format: ${paren}`);
    }
    return (m[1] + m[2]).toUpperCase();
}

export function buildCatalog() {
    const entries = getAllStandardTagEntries();
    const attributes = {};
    for (const e of entries) {
        const tag = bareTag(e.tag);
        if (EXCLUDED_TAGS.has(tag)) {
            continue;
        }
        parseVm(e.vm); // throws on unclassifiable VM — loud failure
        let vr;
        if (VR_SCALAR[e.vr]) {
            vr = e.vr;
        } else if (MULTI_VR[e.vr]) {
            vr = MULTI_VR[e.vr];
        } else {
            throw new Error(`${tag} ${e.name}: unmapped VR code "${e.vr}"`);
        }
        attributes[tag] = { keyword: e.name, vr, vm: e.vm };
    }
    const sorted = Object.fromEntries(
        Object.entries(attributes).sort(([a], [b]) => a.localeCompare(b))
    );
    const dictionaryHash = createHash("sha256")
        .update(JSON.stringify(sorted))
        .digest("hex")
        .slice(0, 16);
    return {
        version: SCHEMA_VERSION,
        dictionaryHash,
        vrFormats: VR_FORMATS,
        attributes: sorted,
        envelope: {
            cardinality: "vm-based", // VM multi -> array, VM 1 -> scalar (D1)
            personName: "componentObject", // {Alphabetic,Ideographic,Phonetic} (D13)
            sequences: "datasetArray", // SQ -> NaturalizedDataset[]
            privateTags: "creatorGrouped", // '<slot>:<creator>' keys (D2b, spec 12.3)
            unknownTags: "preserved", // { vr, Value, rawValue } (spec 12.3)
            rawRetention: "inexactOnly", // raw kept when round-trip inexact (D14)
            bulk: "referenceOrBinary" // {BulkDataURI} | {InlineBinary} | binary
        }
    };
}

export function tsTypeFor(entry) {
    const vrs = Array.isArray(entry.vr) ? entry.vr : [entry.vr];
    const scalars = [...new Set(vrs.map(vr => VR_SCALAR[vr]))];
    const scalar = scalars.join(" | ");
    if (scalar === "NaturalizedDataset[]") {
        return scalar; // sequences are arrays regardless of VM
    }
    const { multi } = parseVm(entry.vm);
    if (!multi) {
        return scalar;
    }
    return scalars.length > 1 ? `(${scalar})[]` : `${scalar}[]`;
}

function tsPropName(keyword) {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(keyword)
        ? keyword
        : JSON.stringify(keyword);
}

export function typesSource(catalog) {
    const lines = [
        "// GENERATED by generate/generate-schema.mjs — DO NOT EDIT.",
        `// Schema version ${catalog.version} (dictionary ${catalog.dictionaryHash}).`,
        "// Naturalized data shape ONLY — this is not a full dcmjs API typing.",
        "",
        "export interface PersonName {",
        "    Alphabetic?: string;",
        "    Ideographic?: string;",
        "    Phonetic?: string;",
        "}",
        "export type BulkDataReference = { BulkDataURI: string };",
        "export type InlineBinaryReference = { InlineBinary: string };",
        "export type BinaryValue = ArrayBuffer | BulkDataReference | InlineBinaryReference;",
        "",
        "export interface NaturalizedDataset {"
    ];
    // Duplicate keywords (rare) collapse to one property; widen the type
    // to the union of every duplicate's computed type.
    const seen = new Map(); // keyword -> {tags: [], types: Set}
    for (const [tag, entry] of Object.entries(catalog.attributes)) {
        const type = tsTypeFor(entry);
        const vrLabel = Array.isArray(entry.vr)
            ? entry.vr.join("/")
            : entry.vr;
        const prev = seen.get(entry.keyword);
        if (prev) {
            prev.tags.push(tag);
            prev.types.add(type);
        } else {
            seen.set(entry.keyword, {
                tags: [tag],
                types: new Set([type]),
                vrLabel,
                vm: entry.vm
            });
        }
    }
    for (const [keyword, info] of seen) {
        const type = [...info.types].join(" | ");
        lines.push(
            `    /** ${info.tags.join(", ")} · VR ${info.vrLabel} · VM ${info.vm} */`
        );
        lines.push(`    ${tsPropName(keyword)}?: ${type};`);
    }
    lines.push(
        "    /** Private ('<slot>:<creator>') and unknown-tag keys (spec 12.3) */"
    );
    lines.push("    [privateOrUnknown: string]: unknown;");
    lines.push("}");
    lines.push("");
    return lines.join("\n");
}

export function jsonSchemaFor(entry, catalog) {
    const vrs = Array.isArray(entry.vr) ? entry.vr : [entry.vr];
    const scalarTs = [...new Set(vrs.map(vr => VR_SCALAR[vr]))];
    let item;
    if (scalarTs.length === 1 && scalarTs[0] === "NaturalizedDataset[]") {
        item = { $ref: "#" };
    } else if (scalarTs.length === 1 && scalarTs[0] === "string") {
        item = { type: "string" };
        const fmt = vrs.length === 1 ? catalog.vrFormats[vrs[0]] : undefined;
        if (fmt && fmt.maxLength) {
            item.maxLength = fmt.maxLength;
        }
        if (fmt && fmt.pattern) {
            item.pattern = fmt.pattern;
        }
    } else if (scalarTs.length === 1 && scalarTs[0] === "number") {
        item = { type: "number" };
    } else {
        item = {}; // PersonName, BinaryValue, unions: annotation-only
    }
    const vm = parseVm(entry.vm);
    const isSq = scalarTs[0] === "NaturalizedDataset[]";
    let prop;
    if (isSq || vm.multi) {
        prop = { type: "array", items: item };
        if (!isSq && vm.min > 1) {
            prop.minItems = vm.min;
        }
        if (!isSq && vm.max !== null && vm.max !== vm.min) {
            prop.maxItems = vm.max;
        }
    } else {
        prop = { ...item };
    }
    prop["x-dicom-vr"] = Array.isArray(entry.vr)
        ? entry.vr.join("/")
        : entry.vr;
    prop["x-dicom-vm"] = entry.vm;
    return prop;
}

export function jsonSchemaSource(catalog) {
    const properties = {};
    const seen = new Set();
    for (const [tag, entry] of Object.entries(catalog.attributes)) {
        if (seen.has(entry.keyword)) {
            continue; // keep first per keyword, matching the d.ts dedup
        }
        seen.add(entry.keyword);
        properties[entry.keyword] = {
            ...jsonSchemaFor(entry, catalog),
            "x-dicom-tag": tag
        };
    }
    const doc = {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        $id: "https://dcmjs.org/schema/naturalized.schema.json",
        title: "dcmjs naturalized dataset",
        "x-dicom-schema-version": catalog.version,
        "x-dicom-dictionary-hash": catalog.dictionaryHash,
        type: "object",
        properties,
        additionalProperties: true
    };
    return JSON.stringify(doc, null, 2) + "\n";
}

export function catalogSource(catalog) {
    const header =
        "// GENERATED by generate/generate-schema.mjs — DO NOT EDIT.\n" +
        "// Normative rule catalog for the naturalized representation (D22).\n" +
        "// Spec: docs/superpowers/specs/2026-07-03-d22-naturalized-schema-design.md\n";
    return `${header}export const naturalizedRules = ${JSON.stringify(
        catalog,
        null,
        2
    )};\n`;
}
