name: Run lint and format check

on:
  - push
  - pull_request

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Check Prettier formatting
        run: pnpm format:check
