name: Run tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 24]
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm run build
